In [56]:
#!/usr/bin/python
# -*- coding: utf-8 -*-
from matplotlib import pyplot as plt
import numpy as np

from IPython.display import Latex, Math, display

import mark

**PCA(特征根求解斐波那契数列)**

[课时27 特征值特征向量这对好基友](http://study.163.com/course/courseLearn.htm?courseId=1050010#/learn/video?lessonId=1003316016&courseId=1050010)

[课时29 如何用特征值分解求Fibonacci数列](http://study.163.com/course/courseLearn.htm?courseId=1050010&from=study#/learn/video?lessonId=1003323035&courseId=1050010)

In [57]:
display(r"Fibonacci sequence such as:")
display(Latex(r"$F_{k+2} = F_{k+1} + F_{k}$"))
display(Latex(r"$F_{k+1} = F_{k+1} + 0$"))
display(r"let's write to matrix mode:")
display(Latex(r"$\begin{bmatrix} \
F_{k+2} \\\
F_{k+1} \
\end{bmatrix} = \overbrace{\begin{bmatrix} \
1 \quad 1 \\\
1 \quad 0 \\\
\end{bmatrix}}^{A} \overbrace{\begin{bmatrix} \
F_{k+1} \\\
F_{k} \
\end{bmatrix}}^{U_{k}} , \quad special. \quad U_{0} = \begin{bmatrix} \
1 \\\
0 \
\end{bmatrix} \
$"))

'Fibonacci sequence such as:'

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

"let's write to matrix mode:"

<IPython.core.display.Latex object>

$由特征向量(A - \lambda I)x = 0 线性相关, 可得\lambda_{1}=\frac{1+\sqrt{5}}{2} \quad \lambda_{2}=\frac{1-\sqrt{5}}{2},\quad代入Ax = \lambda x 方程可得:$

$\begin{equation}
x_{1} + x_{2} = \lambda_{1} x_{1} \\
x_{1} = \lambda_{1} x_{2} \qquad 求得\quad x_{1} = \lambda_{1} \quad x_{2} = 1
\end{equation}$

$\begin{equation}
x_{1} + x_{2} = \lambda_{1} x_{1} \\
x_{1} = \lambda_{1} x_{2} \qquad 求得\quad x_{1} = \lambda_{2} \quad x_{2} = 1
\end{equation}$

$
可得
\overbrace{\begin{bmatrix}
\lambda_{1} \quad \lambda_{2} \\
1 \quad 1
\end{bmatrix}}^{S} \quad,\quad
\overbrace{\begin{bmatrix}
\lambda_{1} \quad 0 \\
0 \quad \lambda_{2}
\end{bmatrix}}^{\land}
, \quad 又 \quad AS = S\land 推广得 \quad A^{N} = S\land^{N}S^{-1}, \quad 故
$

$
U_{k} = A^{k}U_{0} = S\land^{k}S^{-1}U_{0}
$

$很明显当k很大时 \lambda^{k} 取决于大的那个, 即\quad \lambda_{1} \approx 1.618 \quad 为主要成分$

In [58]:
lambda1 = (1+sqrt(5))/2
lambda2 = (1-sqrt(5))/2

S = np.array([[lambda1, lambda2], [1, 1]])
S_inv = np.array([[lambda1, 1], [lambda2, 1]])
land = np.array([[lambda1, 0], [0, lambda2]])
U0 = np.array([[1], [0]])

print S, 'S\n\n', S_inv, 'S_inv\n\n', land, 'land\n\n', U0, 'U0\n\n'

[[ 1.61803399 -0.61803399]
 [ 1.          1.        ]] S

[[ 1.61803399  1.        ]
 [-0.61803399  1.        ]] S_inv

[[ 1.61803399  0.        ]
 [ 0.         -0.61803399]] land

[[1]
 [0]] U0




In [24]:
def have_landN(N):
    landN = land
    for i in range(1, N):
        landN = landN.dot(land)
    return landN

In [55]:
# have_landN填入k参数
Uk = S.dot(have_landN(11)).dot(S_inv).dot(U0)
print Uk, sqrt(Uk[[0]]*Uk[[0]] + Uk[[1]]*Uk[[1]])
print Uk[[0]]/Uk[[1]]

[[ 521.]
 [ 322.]] 612.474489265
[[ 1.61801242]]
